import Header from '@/components/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import Providers from './Providers'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
           {/* Header */}
        <Header />

          {/* Navbar */}
        <Navbar />   

          {/* SearchBox */}
          {children}
        </Providers>
        
        </body>
    </html>
  )
}
// This component serves as the layout template for the application.
// It includes the header, navbar, and search components
// is consistent across all pages.
//Providers is client side, Header, children - service